<?php

function prime_sieve_menu() {
    $items = array();
    $items['prime_sieve'] = array(
        'title' => 'Eratosthenes\'s Prime Sieve',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('prime_sieve_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['sieve_success'] = array(
        'title' => 'Prime Sieve Success',
        'page callback' => 'prime_sieve_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function prime_sieve_generator($max) {
    if($max < 2) {
        return 'No primes';
    }

    //create array of all numbers up to max
    $numbers = array();
    for ($i=2; $i <= $max; $i++) {
        array_push($numbers, $i);
    }

    //sieve primes
    //if index_prime squared <= last value in numbers array stop
    for ($i=0; pow($numbers[$i], 2) <= $numbers[count($numbers) - 1]; $i++) {


        //set index_prime to smallest number not yet sieved
        $index_prime = $numbers[$i];

        //loop through array of numbers
        foreach($numbers as $key=>$item) {
            //remove all multiples of index_prime
            if($item % $index_prime == 0 && $item !== $index_prime) {
                unset($numbers[$key]);
            }
        }

        //reset array keys
        $numbers = array_values($numbers);
    }

    //create array of primes
    $primes = array();
    foreach($numbers as $i) {
        array_push($primes, $i);
    }

    //create string of primes with spaces
    $primes_list = implode(' ', $primes);

    return $primes_list;
}


function prime_sieve_form() {
    $form['max'] = array(
        '#title' => 'Max',
        '#type' => 'textfield',
        '#description' => t('Enter the max number to sieve to'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Sieve it!',
    );
    return $form;
}

function prime_sieve_form_submit($form, &$form_state) {
    $max = $form_state['values']['max'];
    $primes = prime_sieve_generator($max);
    $_SESSION['primes'] = $primes;
    $form_state['redirect'] = 'sieve_success';
}

function prime_sieve_success() {
    $primes = $_SESSION['primes'];
    return '<p>Your primes are: ' . $primes . '</p>';
}
